# Generated by Django 4.0 on 2021-12-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='user id')),
                ('pub_date', models.DateField(verbose_name='date of video')),
                ('video_data', models.BinaryField(verbose_name='video')),
            ],
        ),
    ]
